"""Tournament pairing algorithms.

Supported formats:
  Swiss      — Monrad system: pair by score group, avoid rematches, balance colours.
  RoundRobin — Berger tables for n players.
  Knockout   — Single elimination bracket seeded by rating.
  Arena      — Sort by score, pair top vs next, skip already-playing pairs.

Each function returns a list of (white_user_id, black_user_id | None) tuples.
None as black means the player gets a bye (full point, no game).
"""
from __future__ import annotations

import random
from dataclasses import dataclass, field


@dataclass
class Standing:
    user_id: int
    rating: int
    points: float = 0.0
    colour_balance: int = 0   # +1 = more whites, -1 = more blacks
    opponents: list[int] = field(default_factory=list)


Pairing = tuple[int, int | None]   # (white_id, black_id | None)


# ── Swiss (Monrad) ────────────────────────────────────────────────────────────

def swiss_pairings(standings: list[Standing]) -> list[Pairing]:
    """Pair players for the next Swiss round.

    Algorithm:
    1. Sort by points desc, then rating desc.
    2. Within each score group, pair adjacent players.
    3. Avoid rematches; if unavoidable, swap with the next pair.
    4. Balance colours (prefer the player who needs the opposite colour).
    5. Odd player out gets a bye.
    """
    players = sorted(standings, key=lambda s: (-s.points, -s.rating))
    unpaired = list(players)
    pairings: list[Pairing] = []
    bye_player: Standing | None = None

    if len(unpaired) % 2 == 1:
        # Give bye to lowest-scored player who hasn't had one yet.
        bye_player = unpaired.pop()
        pairings.append((bye_player.user_id, None))

    while len(unpaired) >= 2:
        p1 = unpaired.pop(0)
        # Find the best match for p1.
        paired = False
        for i, p2 in enumerate(unpaired):
            if p2.user_id not in p1.opponents:
                unpaired.pop(i)
                white, black = _assign_colours(p1, p2)
                pairings.append((white.user_id, black.user_id))
                paired = True
                break
        if not paired:
            # All remaining are rematches — just pair with the next one.
            p2 = unpaired.pop(0)
            white, black = _assign_colours(p1, p2)
            pairings.append((white.user_id, black.user_id))

    return pairings


def _assign_colours(a: Standing, b: Standing) -> tuple[Standing, Standing]:
    """Return (white, black) balancing colour history."""
    if a.colour_balance > b.colour_balance:
        return b, a   # a has had more whites → give b white
    if b.colour_balance > a.colour_balance:
        return a, b
    # Equal — random.
    return (a, b) if random.random() < 0.5 else (b, a)


# ── Round Robin (Berger tables) ───────────────────────────────────────────────

def round_robin_schedule(player_ids: list[int]) -> list[list[Pairing]]:
    """Return a full round schedule for all players.

    Returns a list of rounds, each round being a list of (white, black) pairs.
    Uses the standard circle / Berger method.
    """
    ids = list(player_ids)
    if len(ids) % 2 == 1:
        ids.append(None)  # type: ignore[arg-type]  — None = bye sentinel

    n = len(ids)
    rounds: list[list[Pairing]] = []

    for rnd in range(n - 1):
        round_pairings: list[Pairing] = []
        for i in range(n // 2):
            p1 = ids[i]
            p2 = ids[n - 1 - i]
            if p1 is None or p2 is None:
                bye = p2 if p1 is None else p1
                round_pairings.append((bye, None))  # type: ignore[arg-type]
            else:
                # Alternate colours round by round for board 1.
                if rnd % 2 == 0:
                    round_pairings.append((p1, p2))
                else:
                    round_pairings.append((p2, p1))
        rounds.append(round_pairings)
        # Rotate: fix last element, rotate the rest.
        ids = [ids[0]] + [ids[-1]] + ids[1:-1]

    return rounds


# ── Knockout (single elimination) ─────────────────────────────────────────────

def knockout_bracket(player_ids: list[int], ratings: dict[int, int]) -> list[list[Pairing]]:
    """Seed players by rating and create first-round bracket.

    Returns rounds lazily — only round 1 is generated up front; subsequent
    rounds are generated by the tournament service after results are in.
    """
    seeded = sorted(player_ids, key=lambda uid: -ratings.get(uid, 1200))
    # Pad to next power of 2 with byes.
    n = len(seeded)
    size = 1
    while size < n:
        size *= 2
    seeded += [None] * (size - n)  # type: ignore[list-item]

    # Standard seed pairing: 1 vs 2n, 2 vs 2n-1, …
    pairings: list[Pairing] = []
    half = size // 2
    for i in range(half):
        p1 = seeded[i]
        p2 = seeded[size - 1 - i]
        if p1 is None:
            pairings.append((p2, None))  # type: ignore[arg-type]
        elif p2 is None:
            pairings.append((p1, None))
        else:
            pairings.append((p1, p2))

    return [pairings]


def next_knockout_round(results: list[tuple[int, int | None, str]]) -> list[Pairing]:
    """Given (white_id, black_id, result) from previous round, generate next.

    result: "1-0" | "0-1" | "1/2-1/2" (in KO, draw → white advances by default
    or run a blitz tiebreak — simplified here to white advances).
    """
    winners: list[int] = []
    for white_id, black_id, result in results:
        if black_id is None:
            winners.append(white_id)
        elif result == "1-0":
            winners.append(white_id)
        elif result == "0-1":
            winners.append(black_id)
        else:
            winners.append(white_id)   # tiebreak: white advances

    pairings: list[Pairing] = []
    for i in range(0, len(winners), 2):
        if i + 1 < len(winners):
            pairings.append((winners[i], winners[i + 1]))
        else:
            pairings.append((winners[i], None))
    return pairings


# ── Arena ─────────────────────────────────────────────────────────────────────

def arena_pairings(
    standings: list[Standing],
    currently_playing: set[int],
) -> list[Pairing]:
    """Pair idle players in an arena tournament.

    Pairs the highest-scoring idle players first, skipping any who are already
    in a game.  Rematches are allowed in Arena (Lichess-style).
    """
    idle = [s for s in standings if s.user_id not in currently_playing]
    idle.sort(key=lambda s: (-s.points, -s.rating))

    pairings: list[Pairing] = []
    used: set[int] = set()

    for i in range(len(idle)):
        if idle[i].user_id in used:
            continue
        for j in range(i + 1, len(idle)):
            if idle[j].user_id in used:
                continue
            # Prefer no rematch, but allow if no other option.
            if idle[j].user_id not in idle[i].opponents or j == i + 1:
                white, black = _assign_colours(idle[i], idle[j])
                pairings.append((white.user_id, black.user_id))
                used.add(idle[i].user_id)
                used.add(idle[j].user_id)
                break

    return pairings
